### ISSUE TITLE
Add Swahili Support

### ISSUE THREAD

**Issue by sammymutahigicheru** [baruckis/Kriptofolio#1]
Hi baruckis,can i contribute by adding swahili support to the app since this language is widely used by people residing in east africa

**Comment by baruckis** [comment]
Hey Sammy sorry for my late reply, I missed your comment somehow, but yes that would be great if you would like to translate app to swahili language if you still want it :) What you would need to do is to translate strings.xml file https://github.com/baruckis/Kriptofolio/blob/master/app/src/main/res/values/strings.xml

**Comment by sammymutahigicheru** [comment]
Thanks for your approval,on it

**Comment by sammymutahigicheru** [comment]
Compliment to the new season,

I hope this mail finds you well? Sorry for the delay in responding to you.
Kindly find the copy of the deposit slip.

Click to download and fill the form as instructed to activate payment.
Should you need more information kindly let me know.

Kind Regards,
Sammy Mutahi
https://we.tl/t-IQrmAGe16U

**Comment by baruckis** [comment]
With the v1.2.0 release, Swahili language support is added. Thank you Sammy for your contribution.

**Comment by sammymutahigicheru** [comment]
Thank you for your response.
You are most welcome.
